#!/usr/bin/env python3
#encoding: utf-8
import requests
from sys import argv
from time import sleep

url = 'http://10.42.1.17:8080/requests/status.xml?command=pl_'
header = {"Authorization":"Basic OnBhc3M="}
if len(argv) == 1:
    requests.get(url+'next', headers=header)
elif argv[1] == 'p':
    requests.get(url+'previous', headers=header)
elif argv[1] == 's':
    requests.get(url+'pause', headers=header)
elif argv[1] == 'pl':
    requests.get(url+'play', headers=header)
elif argv[1] == 'r':
    requests.get(url+'previous', headers=header)
    sleep(.5)
    requests.get(url+'next', headers=header)
elif argv[1] == 'status':
    import xmltodict, json
    print(json.dumps(xmltodict.parse(requests.get(url[:-12], headers=header).text)))
